/**
 * Nokia TAS Call Direction API
 * The first version of the Nokia TAS Call Direction API is an exciting step forward towards making it easier for developers to have open access to their operator's network.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: openapi.support@nokia.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ClickToCall', 'model/ClickToCallResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ClickToCall'), require('../model/ClickToCallResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.NokiaTasCallDirectionApi) {
      root.NokiaTasCallDirectionApi = {};
    }
    root.NokiaTasCallDirectionApi.ClicktocallApi = factory(root.NokiaTasCallDirectionApi.ApiClient, root.NokiaTasCallDirectionApi.ClickToCall, root.NokiaTasCallDirectionApi.ClickToCallResponse);
  }
}(this, function(ApiClient, ClickToCall, ClickToCallResponse) {
  'use strict';

  /**
   * Clicktocall service.
   * @module api/ClicktocallApi
   * @version 1.0.0
   */

  /**
   * Constructs a new ClicktocallApi. 
   * @alias module:api/ClicktocallApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the clickToCall operation.
     * @callback module:api/ClicktocallApi~clickToCallCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ClickToCallResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a click to call request
     * 
     * @param {module:model/ClickToCall} clickToCall Click to Call object that needs to be sent to the Nokia TAS
     * @param {module:api/ClicktocallApi~clickToCallCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ClickToCallResponse}
     */
    this.clickToCall = function(clickToCall, callback) {
      var postBody = clickToCall;

      // verify the required parameter 'clickToCall' is set
      if (clickToCall == undefined || clickToCall == null) {
        throw new Error("Missing the required parameter 'clickToCall' when calling clickToCall");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['nokia_mn_api_auth'];
      var contentTypes = ['application/json', 'application/xml'];
      var accepts = ['application/xml', 'application/json'];
      var returnType = ClickToCallResponse;

      return this.apiClient.callApi(
        '/callcontrol/v1/clicktocall', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
