/**
 * Nokia TAS Call Direction API
 * The first version of the Nokia TAS Call Direction API is an exciting step forward towards making it easier for developers to have open access to their operator's network.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: openapi.support@nokia.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NokiaTasCallDirectionApi);
  }
}(this, function(expect, NokiaTasCallDirectionApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NokiaTasCallDirectionApi.CallEventFilter();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CallEventFilter', function() {
    it('should create an instance of CallEventFilter', function() {
      // uncomment below and update the code to test CallEventFilter
      //var instane = new NokiaTasCallDirectionApi.CallEventFilter();
      //expect(instance).to.be.a(NokiaTasCallDirectionApi.CallEventFilter);
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instane = new NokiaTasCallDirectionApi.CallEventFilter();
      //expect(instance).to.be();
    });

    it('should have the property criteria (base name: "criteria")', function() {
      // uncomment below and update the code to test the property criteria
      //var instane = new NokiaTasCallDirectionApi.CallEventFilter();
      //expect(instance).to.be();
    });

    it('should have the property addressDirection (base name: "addressDirection")', function() {
      // uncomment below and update the code to test the property addressDirection
      //var instane = new NokiaTasCallDirectionApi.CallEventFilter();
      //expect(instance).to.be();
    });

  });

}));
