/**
 * Nokia TAS Call Direction API
 * The first version of the Nokia TAS Call Direction API is an exciting step forward towards making it easier for developers to have open access to their operator's network.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: openapi.support@nokia.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Participant'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Participant'));
  } else {
    // Browser globals (root is window)
    if (!root.NokiaTasCallDirectionApi) {
      root.NokiaTasCallDirectionApi = {};
    }
    root.NokiaTasCallDirectionApi.CallSessionInformation = factory(root.NokiaTasCallDirectionApi.ApiClient, root.NokiaTasCallDirectionApi.Participant);
  }
}(this, function(ApiClient, Participant) {
  'use strict';




  /**
   * The CallSessionInformation model module.
   * @module model/CallSessionInformation
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CallSessionInformation</code>.
   * @alias module:model/CallSessionInformation
   * @class
   * @param participant {module:model/Participant} 
   */
  var exports = function(participant) {
    var _this = this;

    _this['participant'] = participant;
  };

  /**
   * Constructs a <code>CallSessionInformation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CallSessionInformation} obj Optional instance to populate.
   * @return {module:model/CallSessionInformation} The populated <code>CallSessionInformation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('participant')) {
        obj['participant'] = Participant.constructFromObject(data['participant']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Participant} participant
   */
  exports.prototype['participant'] = undefined;



  return exports;
}));


