/**
 * Nokia TAS Call Direction API
 * The first version of the Nokia TAS Call Direction API is an exciting step forward towards making it easier for developers to have open access to their operator's network.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: openapi.support@nokia.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CallDirectionSubscription'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CallDirectionSubscription'));
  } else {
    // Browser globals (root is window)
    if (!root.NokiaTasCallDirectionApi) {
      root.NokiaTasCallDirectionApi = {};
    }
    root.NokiaTasCallDirectionApi.CallDirectionSubscriptionWrapper = factory(root.NokiaTasCallDirectionApi.ApiClient, root.NokiaTasCallDirectionApi.CallDirectionSubscription);
  }
}(this, function(ApiClient, CallDirectionSubscription) {
  'use strict';




  /**
   * The CallDirectionSubscriptionWrapper model module.
   * @module model/CallDirectionSubscriptionWrapper
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CallDirectionSubscriptionWrapper</code>.
   * @alias module:model/CallDirectionSubscriptionWrapper
   * @class
   * @param callDirectionSubscription {module:model/CallDirectionSubscription} 
   */
  var exports = function(callDirectionSubscription) {
    var _this = this;

    _this['callDirectionSubscription'] = callDirectionSubscription;
  };

  /**
   * Constructs a <code>CallDirectionSubscriptionWrapper</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CallDirectionSubscriptionWrapper} obj Optional instance to populate.
   * @return {module:model/CallDirectionSubscriptionWrapper} The populated <code>CallDirectionSubscriptionWrapper</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('callDirectionSubscription')) {
        obj['callDirectionSubscription'] = CallDirectionSubscription.constructFromObject(data['callDirectionSubscription']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/CallDirectionSubscription} callDirectionSubscription
   */
  exports.prototype['callDirectionSubscription'] = undefined;



  return exports;
}));


